name: build

on:
  push:
    branches:
      - master
      - develop
      - win
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux, win32, win64]
    container: chromaticisobar/pd
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: cd build/${{ matrix.target }} && make
#    - name: Upload shared object
#      uses: actions/upload-artifact@v1
#      with:
#        name: libSDT
#        path: src/SDT/libSDT.so
