name: doxy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  doxygen:
    runs-on: ubuntu-latest
    container: chromaticisobar/doxy
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build docs
      run: doxygen
    - name: Upload docs
      uses: actions/upload-artifact@v1
      with:
        name: doc
        path: doc
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc/html
