name: mac

on:
  push:
    branches:
      - macos

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [macosx]
        platform: [install_core, install_max, install_pd]
        include:
        - target: macosx
          dir: DSTDIR
        - platform: install_core
          plt_name: ""
        - platform: install_pd
          plt_name: _pd
        - platform: install_max
          plt_name: _max
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: cd build/${{ matrix.target }} && make
    - name: Prepare package directory
      run: mkdir SoundDesignToolkit
    - name: Package
      run: cd build/${{ matrix.target }} && make ${{ matrix.platform }} ${{ matrix.dir }}=../../SoundDesignToolkit
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: SDT_${{ matrix.target }}${{ matrix.plt_name }}
        path: SoundDesignToolkit