name: ubuntu

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    container: chromaticisobar/pd
    steps:
    - uses: actions/checkout@v2
    - name: Build shared object
      run: cd build/linux && make
    - name: Upload shared object
      uses: actions/upload-artifact@v1
      with:
        name: libSDT
        path: src/SDT/libSDT.so
